基础设置:
  命中特效: "boom"
  投掷音效: "sound/throw.mp3"
  命中音效: "sound/hit.mp3"

精灵球:
  精灵球:
    名称: "精灵球"
    # 请输入自定义头颅的 url
    头颅: "https://textures.minecraft.net/texture/93e68768f4fab81c94df735e205c3b45ec45a67b558f3884479a62dd3f4bdbf8"
    # 精灵球的描述
    精灵球描述:
      - "右键投掷精灵球，捕捉成功率 50%"
    # 被捕捉的生物信息描述格式
    生物信息描述: "&e%type%: &7%name%"
    # 该精灵球的成功率
    成功率: 50
    # 只有 10 生命值以下的生物才能捕捉
    血量限制: 10
    # 控制允许捕捉的生物
    生物列表:
      # 禁止捕捉 boss 生物(凋零骷髅和末影龙)
      - "Boss:false"
      # 禁止捕捉所有怪物
      # - "Monster:false"
      # 禁止捕捉猪
      # - "Pig:false"
      # 禁止捕捉命名过的生物
      # - "Nameable:false"
  大师球:
    name: "大师球"
    lore:

提示消息:
  捕捉成功: "宠物捕捉成功"
  血量限制: "生命值高于 %health% 时不能捕捉"
  无法捕捉: "该生物无法捕捉"