基础设置:
  投掷力度: 1

精灵球:
  精灵球:
    名称: "<b>精灵球</b>"
    # 请输入自定义头颅的 url
    头颅: "https://textures.minecraft.net/texture/93e68768f4fab81c94df735e205c3b45ec45a67b558f3884479a62dd3f4bdbf8"
    # 精灵球的描述
    精灵球描述:
      - ""
      - "一个用来捕捉生物的精灵球"
      - "一个用来捕捉生物的精灵球"
    # 被捕捉的生物信息描述格式
    生物信息描述: "&e%type%: &7%name%"
    # 该精灵球的成功率
    成功率: 50
    # 如果捕捉失败，精灵球有一定概率消失
    损坏率: 100
    # 只有 10% 生命值以下的生物才能捕捉，填写 -1 则不限制
    血量限制: 10
    # 控制允许/禁止捕捉的生物
    捕捉生物管理:
      # 禁止捕捉 boss 生物(凋零骷髅和末影龙)
      - "Boss:false"
      # 禁止捕捉所有怪物
      # - "Monster:false"
      # 禁止捕捉猪
      # - "Pig:false"
      # 禁止捕捉命名过的生物
      # - "Nameable:false"
      # 禁止捕捉所有生物
      # - "LivingEntity:false"
      # 允许捕捉鸡
      # - "Chicken:true"
  大师球:
    名称: "<b>大师球</b>"
    头颅: "https://textures.minecraft.net/texture/93e68768f4fab81c94df735e205c3b45ec45a67b558f3884479a62dd3f4bdbf8"
    精灵球描述:
      - ""
      - "一个用来捕捉生物的精灵球"
      - "一个用来捕捉生物的精灵球"
    # 被捕捉的生物信息描述格式
    生物信息描述: "&e%type%: &7%name%"
    # 该精灵球的成功率
    成功率: 50
    # 如果捕捉失败，精灵球有一定概率消失
    损坏率: 50
    血量限制: -1
    捕捉生物管理:
      - "Boss:false"

# 提示消息使用 mini message 格式
提示消息:
  捕捉成功: "<entity> 被精灵球抓住了！"
  捕捉失败: "<entity> 巧妙的躲过了精灵球！"
  精灵球损坏: "<entity> 的挣扎把精灵球破坏了！"
  血量限制: "<entity> 的生命值需要在 <health> 以下才能捕捉"
  无法捕捉: "<ball> 无法捕捉 <entity>"
  受到保护: "无法 <entity> 受到了保护"