name: PokeBall
main: com.entiv.pokeballcatch.PokeBallPlugin
version: ${version}
api-version: "1.13"
depend:
  - NBTAPI

libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.0"
  - "org.jetbrains.kotlin:kotlin-reflect:1.7.0"
